ice-lab/icestore

README.md

fix: should encode URL

---

package.json

Publish a new version after changed README.md.

chore: publish 0.1.1

---

.editorconfig
.eslintrc
package.json
src/index.ts
src/store.ts
tests/index.spec.tsx

* 配置eslint的缩进规则为2个空格，与我们的编码规范统一
* 格式化所有文件缩进

chore: fix indent

---

package.json
src/store.ts

关联issue https://github.com/alibaba/ice/issues/2398

fix: throw error

---

README.md
README.zh-CN.md
package.json

Refactor: docs

---

src/store.ts

fix: 修复存量的0.1.x版本上多action执行引起Proxy报错的问题，0.2.x已解决此问题，修复方法详见此[comment](https://github.com/ice-lab/icestore/pull/17#issuecomment-508390316)

fix: apply mutate flag fix from 2.x

---

README.zh-CN.md

docs: optimize

---

middlewares/logger/src/index.ts
package.json
tests/index.spec.tsx
tests/store.spec.tsx
tests/util.spec.tsx

- Issue solved by updating `react-testing-library` to `@testing-library/react`.
- Remove the `sleep()` help function, and use `@testing-library/react`'s `wait()` instead.

fix: failed test (alibaba/ice/issues/2895)

---

package.json

Please merge this PR after #46 .

chore: remove dependency

---

README.md
README.zh-CN.md
examples/todos-ts/src/stores/index.ts
package.json
src/index.tsx
src/store.ts
src/types.ts

API 设计与 applyMiddleware 保持一致，使用方式参考 [《禁用异步状态》](https://github.com/ice-lab/icestore/blob/f3b245b618697ce7800482f3a4271a167b142b37/README.zh-CN.md#%E7%A6%81%E7%94%A8%E5%BC%82%E6%AD%A5%E7%8A%B6%E6%80%81)章节的说明。

feat: 新增 applyOption API 用于禁止 Store 的异步状态

---

examples/todos-ts/src/index.tsx
examples/todos-ts/src/stores/index.ts
examples/todos-ts/src/stores/todos.ts
examples/todos-ts/src/stores/user.ts
src/index.tsx
src/store.ts

在 icestore 中目前没有提供 Store 有依赖关系的调用指引。在实际项目中，目前大家普遍的处理方式是，将多个 Store 都放在更高级别的父组件中，通过封装函数或者使用 useEffect 来实现 Store 的联动。
一个示例：交互触发点在 BComponent，点击后 aStore && bStore 都有数据变更，AComponent && BComponent 都将重新执行。
```tsx
function AComponent(props) {
const { dataSource } = props;
return (
<div>
{dataSource.field}
</div>
);
}
function BComponent(props) {
const { dataSource, doSomething } = props;
return (
<div>
{dataSource.field}
<button onClick={doSomething}>触发点</button>
</div>
);
}
function App() {
const aStore = stores.useStore('aStore');
const bStore = stores.useStore('bStore');
function doSomething() {
const foo = aStore.doSomething(); // 将触发 App 重新执行，AComponent && BComponent 都会重新执行
bStore.doSomething(foo); // 将触发 App 重新执行，AComponent && BComponent 都会重新执行
}
return (
<div>
<AComponent …
```

feat: Store 间相互调用

---

README.md
README.zh-CN.md
examples/todos-ts/src/index.tsx
examples/todos-ts/src/stores/index.ts
examples/todos-ts/src/stores/todos.ts
examples/todos-ts/src/stores/user.ts
package.json
src/index.tsx
src/store.ts

- feat: Store 间相互调用
- docs: Store 内的 Action 说明

Release 0.4.7

---

examples/todos/src/components/Car.tsx
examples/todos/src/index.tsx
examples/todos/src/models/car.ts
examples/todos/src/models/index.ts
examples/todos/tsconfig.json
package.json
src/types.ts

see: https://github.com/ice-lab/icestore/pull/74/files#diff-41df78d86ed4de80aae9b0b9560feb2b

fix: actions && effectsState needs at least one child

---

docs/api.md
docs/recipes.md

docs: fix recipes-docs and api-docs

---

README.md
README.zh-CN.md
docs/api.md
docs/api.zh-CN.md
docs/recipes.md
docs/recipes.zh-CN.md
docs/upgrade-guidelines.zh-CN.md
examples/todos/src/models/car.ts
examples/todos/src/models/index.ts
examples/todos/src/models/todos.ts
examples/todos/src/models/user.ts
examples/todos/src/store.ts

- 补充中文文档；
- 补充了 TypeScript 的示例。

feat: 补充中文文档

---

docs/recipes.md
docs/recipes.zh-CN.md
examples/counter/package.json
examples/todos/package.json
package.json
src/icestore.ts
src/plugins/modelApis.tsx

- fix: 获取模型的条件判断有误
- chore: 模型的参数检测报错信息中显示模型名称
- docs: 补充进阶指南

Release 1.3.4

---

docs/recipes.md
docs/upgrade-guidelines.md
docs/upgrade-guidelines.zh-CN.md
examples/todos/src/components/Todos.tsx
examples/todos/src/components/User.tsx
examples/todos/src/models/todos.ts
examples/todos/src/store.ts
package.json
src/types.ts

- Fix: utility type - ExtractIModelDispatcher*
- Docs: model define upgrade guide for 1.0 to 1.3

Release 1.3.5

---

examples/todos/src/models/todos.ts

https://github.com/ice-lab/icestore/issues/109

fix: special handling of arrays

---

README.md
README.zh-CN.md
docs/qna.md
docs/qna.zh-CN.md

- README.md 添加 ICE 生态章节
- 添加 QA 文档

docs: add QnA

---

package.json

https://github.com/alibaba/ice/issues/5252

fix: add main to pkg

---

docs/api.md
docs/qna.md
examples/counter/src/index.tsx
examples/counter/tsconfig.json
src/types.ts
tsconfig.json

feat: 通过使用 createModel 工具函数创建 model, 在 effects 中使用 this 时可以获得完善的类型提示

---

README.en.md
README.md
docs/recipes.md
examples/counter/src/index.tsx
src/types.ts

feat: 增加dispatch和rootState的类型提示

---

.eslintrc.js
README.en.md
README.md
docs/api.md
docs/qna.md
docs/recipes.md
examples/classComponent/package.json
examples/classComponent/src/models/user.ts
examples/counter/package.json
examples/counter/src/index.tsx
examples/counter/tsconfig.json
examples/migration-redux-1/package.json
examples/migration-redux-2/package.json
examples/migration-redux-3/package.json
examples/migration-redux-4/package.json
examples/todos/package.json
examples/todos/src/components/AddTodo.tsx
examples/todos/src/models/todos.ts
examples/todos/src/models/visibilityFilter.ts
examples/withModel/package.json
examples/withModel/src/index.tsx
package.json
src/types.ts
tests/helpers/createHook.tsx
tsconfig.json

- feat: createModel API for ts type
- feat: dispatch and rootState ts type

Release 2.0.2

---

docs/api.md

增加通过断言的方式指定 state 的类型的文档示例，方便在消费 state 的时候获得更好的类型提示

docs: state type
